# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

  create_table "alt_widgets", :force => true do |t|
    t.column "name",         :string
    t.column "title",        :string
    t.column "calc",         :text
    t.column "last_used_at", :datetime
    t.column "views",        :integer
    t.column "data",         :text
  end

  create_table "invites", :force => true do |t|
    t.column "message",          :string
    t.column "inviter_user_id",  :integer
    t.column "accepter_user_id", :integer
    t.column "token",            :string
  end

  create_table "meetings", :force => true do |t|
    t.column "name",           :string
    t.column "cents_per_hour", :integer
    t.column "currency",       :string
    t.column "attendance",     :integer
    t.column "owner_cookie",   :string
  end

  create_table "notes", :force => true do |t|
    t.column "meeting_id", :integer
    t.column "created_at", :datetime
    t.column "stopped_at", :datetime
    t.column "descr",      :string
  end

  create_table "periods", :force => true do |t|
    t.column "meeting_id", :integer
    t.column "created_at", :datetime
    t.column "stopped_at", :datetime
    t.column "descr",      :string
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

end
