# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "alt_widgets", :force => true do |t|
    t.column "name",         :string
    t.column "title",        :string
    t.column "calc",         :string
    t.column "last_used_at", :datetime
    t.column "views",        :integer
  end

  create_table "meetings", :force => true do |t|
    t.column "name",           :string
    t.column "cents_per_hour", :integer
    t.column "currency",       :string
    t.column "attendance",     :integer
  end

  create_table "notes", :force => true do |t|
    t.column "meeting_id", :integer
    t.column "created_at", :datetime
    t.column "stopped_at", :datetime
    t.column "descr",      :string
  end

  create_table "periods", :force => true do |t|
    t.column "meeting_id", :integer
    t.column "created_at", :datetime
    t.column "stopped_at", :datetime
    t.column "descr",      :string
  end

end
